### ISSUE TITLE
启动mymon，dashboard不显示数据曲线

### ISSUE THREAD

**Issue by shuaifes** [open-falcon/mymon#12]
配置好mymon，并成功启动，但是dashboard上面却没有点，这是什么问题，是需要脚本么？

**Comment by laiwei** [comment]
mymon需要放到crontab中定期运行。

**Comment by Aaron199** [comment]
我也出现这种情况，已经放到crontab，但是还是没有数据曲线，mymon.log里是有日志，tcpdump抓包也有在传输json串
