### ISSUE TITLE
go get导致的 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by willre** [open-falcon/mymon#25]
系统版本
CentOS Linux release 7.2.1511 (Core)

golang版本
 go version
go version go1.9.4 linux/amd64

安装源
yum info golang
已加载插件：fastestmirror
Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
已安装的软件包
名称    ：golang
架构    ：x86_64
版本    ：1.9.4
发布    ：1.el7
大小    ：6.8 M
源    ：installed
来自源：base
简介    ： The Go Programming Language
网址    ：http://golang.org/
协议    ： BSD and Public Domain
描述    ： The Go Programming Language.

# $GOPATH 和 $GOROOT 设置
GOROOT=/usr/lib/golang
GOPATH=/opt/golang

报错信息：
命令执行时路径  /opt/golang/src/github.com/open-falcon/mymon

[root@f mymon]# go get ./... && echo ok
# golang.org/x/sys/unix
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x97ca2b]

goroutine 1 [running]:
cmd/compile/internal/gc.dumpasmhdr()
	/usr/lib/golang/src/cmd/compile/internal/gc/export.go:389 +0x2ab
cmd/compile/internal/gc.Main(0xb770d0)
	/usr/lib/golang/src/cmd/compile/internal/gc/main.go:633 +0x280d
main.main()
	/usr/lib/golang/src/cmd/compile/main.go:49 +0x95
[root@f mymon]#

不明白为什么执行 go get 都会得到一个 panic 错误
请问如何解决呢？

**Comment by sylzd** [comment]
可以试试新版本的mymon

**Comment by willre** [comment]
好的
