### ISSUE TITLE
mymon是否支持老版本的openfalon？

### ISSUE THREAD

**Issue by willre** [open-falcon/mymon#26]
我看readme中没有说明
我现在使用的openfalcon 还没有升级到v0.2  
老版本使用过程中是否会出现问题？

**Comment by MistShi** [comment]
@willre ，数据结构没有变化，应该是可以支持的

**Comment by willre** [comment]
好的谢谢

**Comment by MistShi** [comment]
新版本已经merge，可以试用有问题
