### ISSUE TITLE
go get报错，ssdb问题

### ISSUE THREAD

**Issue by Ezail3** [open-falcon/mymon#36]
[root@VM_0_4_centos mymon]# go get ./...
src/github.com/ssdb/gossdb/test.go:7:2: local import "./ssdb" in non-local package

这个是什么问题没看懂，求指导，谢谢

**Comment by martianzhang** [comment]
mymon已经将外部依赖的包添加至vendor中，无需再次`go get ./...`。

需要确认一下代码下载的目录是否为${GOPATH}/src/github.com/open-falcon/mymon，以及当前使用的Go版本，建议使用1.10或以上版本。

**Comment by Ezail3** [comment]
> mymon已经将外部依赖的包添加至vendor中，无需再次`go get ./...`。
> 
> 需要确认一下代码下载的目录是否为${GOPATH}/src/github.com/open-falcon/mymon，以及当前使用的Go版本，建议使用1.10或以上版本。

谢谢，指导，问题已解决
