### ISSUE TITLE
请问一下，关于主从延迟的问题。

### ISSUE THREAD

**Issue by lycclsltt** [open-falcon/mymon#37]
seconds_binds_master 是不准的，是不能完全依赖的。请问mymon如何监控主从延迟?支持从pt-heartment获取监控数据吗？

**Comment by martianzhang** [comment]
mymon中有一个监控项叫`Heartbeats_Behind_Master`，可用于发现由于网络异常导致的同步延迟时间不准确的问题，这个监控项是从pt-heartbeat生成的mysql.heartbeat表中读取ts字段值与当前时间相减后上报。如果没有这个表mysql.heartbeat这个表程序会上报-1，表示未采集到。

目前文档中描述得并不详细，后面会补充完善这块的说明。
