### ISSUE TITLE
2020/03/12 19:08:14.880 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"

### ISSUE THREAD

**Issue by 13691432320** [open-falcon/mymon#58]
cat myMon.log
2020/03/12 19:08:14.880 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:11:09.089 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:21:04.166 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:21:05.800 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:21:08.247 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:26:31.090 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:56:12.483 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:56:13.374 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:56:13.976 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 19:56:19.560 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
2020/03/12 20:02:29.209 [E] [main.go:88] Error: Received #1227 error from MySQL server: "Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation"
You have mail in /var/spool/mail/root

**Comment by laiwei** [comment]
请检查 MySQL 用户权限。
